### ISSUE TITLE
pip3 install bitfinex-v2 returnes file not found - README.md

### ISSUE THREAD

**Issue by nhondong** [ohenrik/bitfinex#10]
Command: pip3 install bitfinex-v2 returns:

Collecting bitfinex-v2
  Downloading https://files.pythonhosted.org/packages/a8/a0/e10703a05c2ed27d07ce4d5bdaabda3ed60030706bc2f1e6c935fe71cc7e/bitfinex-v2-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-62awd5et/bitfinex-v2/setup.py", line 15, in <module>
        with open("README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

**Comment by nhondong** [comment]
pip3 install git+https://github.com/ohenrik/bitfinex.git works, but i still get: 

from bitfinex.websockets import WssClient
    from bitfinex.websockets import WssClient
ModuleNotFoundError: No module named 'bitfinex.websockets'; 'bitfinex' is not a package

**Comment by nhondong** [comment]
OMG, this was a beginner Error. 
I had a file named bitfinex.py in my scriptfolder...

Sorry for that.

**Comment by ohenrik** [comment]
this is now fixed :)
