### ISSUE TITLE
Stop limit orders via websocket v2 not supported

### ISSUE THREAD

**Issue by gaorufeng** [ohenrik/bitfinex#16]
new_order("LIMIT", "tEOSUSD", "5", "4") is OK!, I don't know how to support  stop limit for new_order().

update:

I edit client.py 

copy new_order_op to new_order_op_stop_limit
```

def new_order_op_stop_limit(self, order_type, pair, amount, price, stop_limit_price,hidden=0, flags=None):

 #add  'price_aux_limit':stop_limit_price

    flags = flags or []
    client_order_id = wss_utils.UtcNow()
    return {
        'cid': client_order_id,
        'type': order_type,
        'symbol': wss_utils.order_pair(pair),
        'amount': amount,
        'price': price,
        'price_aux_limit':stop_limit_price,  
        'hidden': hidden,
        "flags": sum(flags)
    }
```
copy new_order to new_order_stop_limit()

```
def new_order_stop_limit(self, order_type, pair, amount, price, stop_limit_price, hidden=0, flags=list()):

    operation = self.new_order_op_stop_limit(order_type, pair, amount, price, stop_limit_price, 0, flags)
    data = [0,wss_utils.get_notification_code('order new'),None,operation]
    payload = json.dumps(data, ensure_ascii = False).encode('utf8')
    self.factories["auth"].protocol_instance.sendMessage(payload, isBinary=False)
    return operation["cid"]   
```

if price $5.0

exch_order = self.mywss.new_order_stop_limit("STOP LIMIT", "tEOSUSD", "4", "6","6.2")

exch_order = self.mywss.new_order_stop_limit("STOP LIMIT", "tEOSUSD", "-6", "4","3.9")

That's OK. Sorry, my English is not good

**Comment by ohenrik** [comment]
This is a good point, at the moment we are making it impossible to place complex orders over the websocket api. We’ll fix this soon, however a PR would be much appreciated if you would want to contribute :)
