### ISSUE TITLE
Testing: Fix problem with pyOpenSSL and HTTPpretty during testing.

### ISSUE THREAD

**Issue by ohenrik** [ohenrik/bitfinex#2]
Consider switching completely to python-mocket to fix problems when running tests.

A temporary (but annoying) fix is to uninstall pyOpenSSL before running tests:

```
pip uninstall pyOpenSSL
pytest -v
pip install pyOpenSSL
``` 

https://github.com/mindflayer/python-mocket/issues/65

**Comment by mindflayer** [comment]
I've just released `mocket==2.3.0` which should fix the issues with `pyOpenSSL`.

**Comment by ohenrik** [comment]
Thank you for letting me know, i have recently switched over to using `request_mock` in combination with pytest instead. But it’s good to know that it is fixed for future cases. :)
