### ISSUE TITLE
Sample code to get bid price using wssclient

### ISSUE THREAD

**Issue by lkthomas** [ohenrik/bitfinex#31]
Can you show us some sample code which contains a filter to put bid price into a variable please?

**Comment by dantimofte** [comment]
from bitfinex import WssClient
import asyncio

def process_ticker(ticker_data):
    if isinstance(ticker_data, list) and ticker_data[1] != 'hb':
        bid_price = ticker_data[1][0]
        print(f'bid price is {bid_price}')

mywss = WssClient()
mywss.start()
mywss.subscribe_to_ticker("BTCUSD", process_ticker)

# this is an infinite loop to prevent the program from finishing
asyncio.get_event_loop().run_forever()
