### ISSUE TITLE
0 values of counter in orderbook

### ISSUE THREAD

**Issue by andrebrener** [ohenrik/bitfinex#36]
Hi - I'm using the websocket endpoints to get the orderbook and trades.

I have some questions regarding its functioning:
1. I see that the first return is the whole (filtered by limits) orderbook and then each forward message is an update to that. I understand that those new messages are new orders. In the case of orders that had been executed, do I have to check that with the trades?

2. I see in the orderbook messages that there are 0 values in the counter. For example: [744498, [9342, 0, 1]]. What does this mean? I recognized that when the counter is 0, the amount is either -1 or 1, but couldn't get its meaning.

3. In the trades endpoint, the first message is a large one with many trades, why is that? Are these trades from the last x minutes?

Thanks

**Comment by dantimofte** [comment]
Hello, a count of 0 for aggregated books mean you have to remove the price from your book . In case of raw order book a price of 0 means you have to remove the specific order by id from your book.
https://docs.bitfinex.com/reference#ws-public-order-books
https://docs.bitfinex.com/reference#ws-public-raw-order-books

for point 3 . yes you will receives a snapshot with the most recent trades executed 
https://docs.bitfinex.com/reference#ws-public-trades

you can find more information here : https://docs.bitfinex.com/docs
