### ISSUE TITLE
V1 Orders

### ISSUE THREAD

**Issue by NescienceSoftware** [ohenrik/bitfinex#45]
Ive been trying to get a simple order function working and with a variety of formattings have had no luck. 

I went as far as copy pasting the example code for v1 ordering and ensuring I had enough USD to cover the .01 btc and no luck, no orders show up. 

Does this just mean that the v1 api is no longer fully operable or am I doing something wrong?

from bitfinex import WssClient, ClientV2, ClientV1

key = 'redacted'
secret = 'redacted'
client = ClientV1(key,secret, nonce_multiplier=999999.15)
symbol = 'ethusd'        # Currency pair to trade
amount = '.15'            # Amount to buy
price = '175'          # Buy price
side = 'sell'             # Buy or sell
ord_type = 'exchange market' # Which type
client.place_order(amount, price, side, ord_type, symbol, exchange='bitfinex')

**Comment by dantimofte** [comment]
What is the output from place_order ? can you show me what the output/error is ?

**Comment by NescienceSoftware** [comment]
If I remember correctly no errors + I didnt save the full json response at the time. It just hung/the order was not placed after passing correct parameters to the function. Sorry, I know that is not nearly as much of a help. I couldnt personally find the issue in the wrapper myself either.

I moved on to CCXT so have not attempted again recently, but if you find anything that could be the cause I would definitely be interested, CCXT can be unbearingly slow.

**Comment by dantimofte** [comment]
i checked you code and the only thing missing was "from bitfinex import ClientV1" at the beggingin.
if you give it a try and show me the output i'll be happy to help you

**Comment by dantimofte** [comment]
i added a set of api key to see what message i get after the error that api key is invalid.  This was the error : `{'message': 'Key amount should be a decimal number, e.g. "123.456"'}`
after i changed the amount to `amount = '.15'` i got the message `{'message': 'Invalid order: not enough exchange balance for -0.15 ETHUSD at 143.25'}`

**Comment by dantimofte** [comment]
Issue does  not reproduce and no answer fromop
