### ISSUE TITLE
authenticated api error

### ISSUE THREAD

**Issue by newforte** [ohenrik/bitfinex#49]
I am trying to make a basic authenticated  api and getting  error.

from bitfinex import ClientV2 as Client2

BTFXCLIENT = Client2('api656j56ejejKey', 'apiSec56je56jjj56j5ret')
BTFXCLIENT.active_positions()

**Comment by dantimofte** [comment]
Can you give me more details? 
What are you Operating system, python version , error  you  receive ?

**Comment by newforte** [comment]
OS: win10 
Python 3.8.5
Run the code in Anaconda Navigator
Error refer the picture
![image](https://user-images.githubusercontent.com/36847786/132115242-d80e0519-b242-4ef2-aa2c-c56e16ea32cb.png)

**Comment by dantimofte** [comment]
You have used the same api keys with a  different library or a different nonce multiplier.  You could try to instantiate with a higher nonce multiplier :  
BTFXCLIENT = Client2('api656j56ejejKey', 'apiSec56je56jjj56j5ret', nonce_multiplier=2.0)
BTFXCLIENT.active_positions()

I recommend that you create a new api key for this and use different api-keys for different things : one for mobile app, one for each trading system

**Comment by newforte** [comment]
Thanks a lot!
