### ISSUE TITLE
Feature Request: Add books and raw books endpoint of websocket API

### ISSUE THREAD

**Issue by zzxxtt** [ohenrik/bitfinex#6]
Thank you for your effort, please considering add books and raw books endpoint of websocket API. Since request order book with REST api very often will be limit on bitfinex. Use websocket API can get realtime orderbook. 
It need to find a way to effieciently organize the order book of different coins, and update them when new websocket data received. I think It also need to implement checksums function to make sure the local order book is correct.
Please considering add this feature, thank you.

reference:
https://docs.bitfinex.com/v2/reference#ws-public-order-books
http://blog.bitfinex.com/api/bitfinex-api-order-books-checksums/

**Comment by ohenrik** [comment]
I might be able to add this later in august or start of september. But feel free to create a pull request if you have the time for it :)
