### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by nhondong** [ohenrik/bitfinex#8]
Hi,
when I execute the following code, I get the data, but I even get the errormessage: 
from bitfinex import ClientV2 as Client
ImportError: cannot import name 'ClientV2'

Code:
```
from bitfinex import ClientV2 as Client
client = Client(
os.environ.get('BITFINEX_KEY'),
os.environ.get('BITFINEX_SECRET')
)

client.ticker('tBTCUSD')
```
Any Ideas?

**Comment by ohenrik** [comment]
The pypi package was not updated to reflect the documentation. Sorry, this is now corrected. you can update to v0.5.1 now :)
